'use client';

import React, { forwardRef, useState, useEffect } from 'react';
import { useAuthStore } from '@/store/auth-store';
import { useOrgStore } from '@/store/org-store';

interface PrintLayoutProps {
  title: string;
  subtitle?: string;
  children?: React.ReactNode;
  orientation?: 'portrait' | 'landscape';
  preview?: boolean;
  orgOverride?: any;
}

export const PrintLayout = forwardRef<HTMLDivElement, PrintLayoutProps>(
  ({ title, subtitle, children, orientation = 'portrait', preview = false, orgOverride }, ref) => {
    const { user } = useAuthStore();
    const { org: storeOrg } = useOrgStore();
    const org = orgOverride || storeOrg;
    const [currentDate, setCurrentDate] = useState<Date | null>(null);

    useEffect(() => {
      setCurrentDate(new Date());
    }, []);
    
    return (
      <div ref={ref} className={`print-layout-container bg-white text-black min-h-screen relative font-sans ${preview ? 'border shadow-xl rounded-md overflow-hidden' : 'hidden print:block'}`}>
        
        {/* Official Government Header */}
        <div className="w-full bg-[#c21f4c] text-white p-6 flex flex-col items-center justify-center text-center rounded-t-sm shadow-sm" style={{ WebkitPrintColorAdjust: 'exact', printColorAdjust: 'exact' }}>
          
          <img src={org?.official_logo_url || '/logo.png'} alt="Official Logo" className="w-24 h-24 mb-4 object-contain" onError={(e) => e.currentTarget.style.display = 'none'} />
          
          {org?.name_si && (
            <h1 className="text-3xl font-black tracking-wide leading-tight mb-2 drop-shadow-sm">
              {org.name_si}
            </h1>
          )}
          {org?.name_ta && (
            <h1 className="text-2xl font-bold tracking-wide leading-tight mb-2 drop-shadow-sm">
              {org.name_ta}
            </h1>
          )}
          <h2 className="text-2xl font-bold tracking-wider uppercase mb-2 text-white/95">
            {org?.name_en || 'Organization Name'}
          </h2>
          
          <div className="flex flex-wrap gap-3 items-center justify-center text-sm font-semibold text-white/90 uppercase tracking-widest mb-2">
            <p>Government of Sri Lanka</p>
            {org?.telephone && (
              <>
                <span className="w-1.5 h-1.5 rounded-full bg-white/50" />
                <p>Tel: {org.telephone}</p>
              </>
            )}
            {org?.email && (
              <>
                <span className="w-1.5 h-1.5 rounded-full bg-white/50" />
                <p>{org.email}</p>
              </>
            )}
          </div>

          <p className="text-xs text-white/80 uppercase tracking-widest mb-4">
            {org?.system_name || 'ANTIGRAVITY'} {org?.system_subtitle || 'Government Store Management System'}
          </p>
          
          <div className="w-full max-w-2xl border-t border-white/20 pt-4 mt-2 flex flex-col items-center">
            <h3 className="text-xl font-bold uppercase">{title}</h3>
            {subtitle && <p className="text-sm opacity-90">{subtitle}</p>}
          </div>

          <div className="absolute top-4 right-4 text-right text-[10px] text-white/80 space-y-0.5 font-mono">
            <p>Generated: {new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</p>
            <p>By: {user?.name || 'System User'}</p>
            <p>Doc ID: {Math.random().toString(36).substring(2, 8).toUpperCase()}</p>
          </div>
        </div>

        {/* Content Area */}
        <div className="p-8">
          <style dangerouslySetInnerHTML={{__html: `
            @page { size: ${orientation === 'landscape' ? 'A4 landscape' : 'A4 portrait'}; margin: 0; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .data-table th { background-color: #c21f4c !important; color: white !important; font-weight: bold; }
            .data-table tbody tr:nth-child(even) { background-color: #f9f9f9 !important; }
            .data-table tbody tr:nth-child(odd) { background-color: #ffffff !important; }
          `}} />
          {children}
        </div>

        {/* Official Government Footer */}
        <div className={`${preview ? 'absolute' : 'fixed'} bottom-0 w-full p-4 border-t-2 border-[#c21f4c] flex justify-between items-end bg-white`}>
          <div className="text-[10px] text-gray-500 space-y-1">
            <p className="font-bold text-[#c21f4c] uppercase">{org?.name_en || 'ORGANIZATION NAME'}</p>
            <p>{org?.system_name || 'ANTIGRAVITY'} {org?.system_subtitle || 'Government Store Management System'}</p>
            <p>Generated by {user?.name || 'System User'}</p>
            <p className="text-[11px] font-semibold text-gray-800 pt-1">Powered by Nikaweratiya Pradheshiya Sabha</p>
          </div>
          
          <div className="flex flex-col items-center">
            {/* Dynamic QR Verification Placeholder for Web Print */}
            <img src={'https://api.qrserver.com/v1/create-qr-code/?size=50x50&data=VERIFY-' + new Date().getTime()} alt="QR" className="w-12 h-12 mb-1" />
            <span className="text-[8px] text-gray-400">Scan to Verify</span>
          </div>
        </div>
      </div>
    );
  }
);

PrintLayout.displayName = 'PrintLayout';

