<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #006838; padding-bottom: 10px; }
        .logo { max-width: 80px; margin-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; margin: 0; color: #006838; }
        .subtitle { font-size: 14px; margin: 5px 0 0 0; }
        .details-table { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        .details-table td { padding: 4px; vertical-align: top; }
        .details-table .label { font-weight: bold; width: 30%; color: #555; }
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .items-table th, .items-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .items-table th { background-color: #f8f9fa; font-weight: bold; color: #006838; }
        .items-table td.right { text-align: right; }
        .signatures { width: 100%; margin-top: 50px; }
        .signatures td { width: 33%; text-align: center; vertical-align: bottom; height: 80px; }
        .signature-line { border-top: 1px solid #333; margin: 0 20px; padding-top: 5px; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{ $organization_name ?? 'Government Store' }}</h1>
        <h2 class="subtitle">{{ $title }}</h2>
    </div>

    <table class="details-table">
        @foreach($details as $key => $value)
            <tr>
                <td class="label">{{ $key }}:</td>
                <td>{{ $value }}</td>
            </tr>
        @endforeach
    </table>

    @if(isset($items) && count($items) > 0)
    <table class="items-table">
        <thead>
            <tr>
                <th>Item Code</th>
                <th>Description</th>
                <th class="right">Quantity</th>
                @if(isset($show_price) && $show_price)
                <th class="right">Unit Price</th>
                <th class="right">Total</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
            <tr>
                <td>{{ $item['code'] }}</td>
                <td>{{ $item['name'] }}</td>
                <td class="right">{{ $item['quantity'] }} {{ $item['unit'] ?? '' }}</td>
                @if(isset($show_price) && $show_price)
                <td class="right">{{ number_format($item['price'], 2) }}</td>
                <td class="right">{{ number_format($item['total'], 2) }}</td>
                @endif
            </tr>
            @endforeach
        </tbody>
        @if(isset($show_price) && $show_price && isset($total_amount))
        <tfoot>
            <tr>
                <th colspan="4" class="right">Grand Total:</th>
                <th class="right">{{ number_format($total_amount, 2) }}</th>
            </tr>
        </tfoot>
        @endif
    </table>
    @endif

    <table class="signatures">
        <tr>
            <td><div class="signature-line">Prepared By</div></td>
            <td><div class="signature-line">Checked By</div></td>
            <td><div class="signature-line">Authorized By</div></td>
        </tr>
    </table>

    <div class="footer">
        Generated by ANTIGRAVITY Store Management System on {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
